const $=s=>document.querySelector(s),state={requests:[],selected:null};
const labels={rating:'Cock rating video',personal_video:'Personalised video',story:'Erotic short story',story_narrated:'Story + narration',roleplay_kink:'Kink or roleplay',other:'Something else'};
const money=c=>c?new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(c/100):'Not quoted';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const active=new Set(['new','reviewing','quoted','accepted','creating','ready']);
function summaries(){const r=state.requests;$('#new-total').textContent=r.filter(x=>x.status==='new').length;$('#quoted-total').textContent=r.filter(x=>x.status==='quoted'&&x.payment_status==='unpaid').length;$('#creating-total').textContent=r.filter(x=>['accepted','creating'].includes(x.status)).length;$('#ready-total').textContent=r.filter(x=>x.status==='ready').length}
function render(){const q=$('#custom-search').value.toLowerCase(),f=$('#status-filter').value;const rows=state.requests.filter(x=>(f==='all'||(f==='active'?active.has(x.status):x.status===f))&&`${x.reference} ${x.guest_name} ${x.request_type} ${x.brief}`.toLowerCase().includes(q));$('#custom-status').hidden=rows.length>0;$('#custom-list').hidden=!rows.length;$('#custom-status').textContent=state.requests.length?'No requests match that view.':'No custom requests yet.';$('#custom-list').innerHTML=rows.map(x=>`<button class="request-row" data-id="${x.id}"><span class="ref">${esc(x.reference)}</span><span class="request-name"><strong>${esc(x.guest_name)}</strong><span>${esc(labels[x.request_type]||x.request_type)}</span></span><span class="request-price">${money(x.quote_cents)}</span><span class="status-pill">${esc(x.status)}</span><span>›</span></button>`).join('')}
async function load(){try{const r=await fetch('/api/office-customs',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);state.requests=d.requests||[];summaries();render()}catch(e){$('#custom-status').textContent=e.message}}
function openRequest(x){state.selected=x;$('#request-title').textContent=`${x.guest_name} · ${x.reference}`;$('#request-detail').innerHTML=`<div class="detail-grid"><div><span>REQUEST</span><p>${esc(labels[x.request_type]||x.request_type)}</p></div><div><span>BUDGET</span><p>${esc(x.budget_band||'Not supplied')}</p></div><div><span>CONTACT</span><p>${esc(x.contact_method)} · ${esc(x.contact_value)}</p></div><div><span>DEADLINE</span><p>${esc(x.deadline||'No deadline')}</p></div><div><span>NAME TO USE</span><p>${esc(x.personal_name||'None')}</p></div><div><span>FORMAT</span><p>${esc(x.format_details||'—')}</p></div><div class="wide"><span>THE BRIEF</span><p>${esc(x.brief)}</p></div></div>`;const f=$('#custom-form');f.id.value=x.id;f.quote.value=x.quote_cents?x.quote_cents/100:'';f.amount_paid.value=x.amount_paid_cents?x.amount_paid_cents/100:'';f.payment_status.value=x.payment_status;f.status.value=x.status;f.delivery_url.value=x.delivery_url||'';f.private_notes.value=x.private_notes||'';$('#form-error').textContent='';$('#custom-drawer').hidden=false}
function close(){ $('#custom-drawer').hidden=true;state.selected=null }
$('#custom-list').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openRequest(state.requests.find(x=>x.id===Number(b.dataset.id)))});$('#custom-search').addEventListener('input',render);$('#status-filter').addEventListener('change',render);document.querySelectorAll('[data-close-drawer]').forEach(b=>b.addEventListener('click',close));
$('#custom-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),body={id:Number(f.get('id')),quote_cents:Math.round(Number(f.get('quote')||0)*100),amount_paid_cents:Math.round(Number(f.get('amount_paid')||0)*100),payment_status:f.get('payment_status'),status:f.get('status'),delivery_url:f.get('delivery_url'),private_notes:f.get('private_notes')};try{const r=await fetch('/api/office-customs',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);close();await load();const t=$('#toast');t.textContent='Request saved — the Ledger is up to date.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}catch(err){$('#form-error').textContent=err.message}});
document.querySelector('[data-open-menu]')?.addEventListener('click',()=>document.body.classList.add('menu-open'));document.querySelectorAll('[data-close-menu]').forEach(b=>b.addEventListener('click',()=>document.body.classList.remove('menu-open')));load();
